"""Generate THIRD-PARTY-LICENSES.txt for Celbridge.

Lists every third-party component that ships in the app: the NuGet packages that put files into the
build output, read from the restore output of the application project, and the bundled components
recorded in manifest.toml. Each entry gives the version, license, source and copyright notice, and the
file ends with the full license texts and the third-party notices that components ask to be reproduced.

Anything that needs a decision is reported as an issue, and the file is only written once no issues
remain. Run with --check to report without writing.
"""

import argparse
import fnmatch
import hashlib
import json
import os
import re
import sys
import tomllib
import xml.etree.ElementTree as ElementTree
from dataclasses import dataclass, field
from pathlib import Path

SKILL_FOLDER = Path(__file__).resolve().parent
MANIFEST_PATH = SKILL_FOLDER / "manifest.toml"
LICENSE_TEXTS_FOLDER = SKILL_FOLDER / "license-texts"
OUTPUT_FILE_NAME = "THIRD-PARTY-LICENSES.txt"

SHIPPED_ASSET_KEYS = [
    "runtime",
    "native",
    "runtimeTargets",
    "resource",
    "contentFiles",
]
EXPRESSION_OPERATORS = {
    "AND",
    "OR",
}
SKIPPED_FOLDER_NAMES = {
    ".celbridge",
    ".git",
    ".venv",
    "__pycache__",
    "bin",
    "node_modules",
    "obj",
}
VENDORED_FOLDER_NAMES = {
    "lib",
    "min",
    "vendor",
}
FONT_EXTENSIONS = {
    ".otf",
    ".ttf",
    ".woff",
    ".woff2",
}
NOTICES_FILE_PATTERN = re.compile(r"^(notices?|third-?party-?notices?)(\.(txt|md))?$", re.IGNORECASE)
LICENSE_FILE_PATTERN = re.compile(r"^(licen[cs]e|copying|ofl|notice)", re.IGNORECASE)
NUGET_LICENSE_URL_PATTERN = re.compile(r"^https?://licenses\.nuget\.org/(.+)$", re.IGNORECASE)
LICENSE_REFERENCE_PATTERN = re.compile(r"LicenseRef-([A-Za-z0-9.-]+)")

HEADER = """THIRD-PARTY SOFTWARE NOTICES AND LICENSES

Celbridge includes the third-party software listed below. Each entry gives the component's version,
license, source and copyright notice. The full text of each license, and the third-party notices that
components ask to be reproduced, follow the list.

This file is generated by the update-third-party-licenses skill in the Celbridge repository. Change the
skill's manifest rather than editing this file."""


@dataclass
class Issue:
    """A problem that needs a decision before the file can be written."""

    subject: str
    message: str


@dataclass
class PackageMetadata:
    """The nuspec fields a notice needs."""

    authors: str = ""
    copyright: str = ""
    license_type: str = ""
    license: str = ""
    license_url: str = ""
    project_url: str = ""
    repository_url: str = ""


@dataclass
class Entry:
    """One listed component with everything its notice needs."""

    name: str
    versions: list[str]
    license_expression: str
    source: str
    copyright_lines: list[str]
    note: str = ""
    license_file_text: str = ""
    notices_texts: list[str] = field(default_factory=list)


def find_repository_root() -> Path:
    """Return the repository root, found by walking up from the skill folder to Celbridge.slnx."""
    folder = SKILL_FOLDER
    while folder != folder.parent:
        if (folder / "Celbridge.slnx").exists():
            return folder
        folder = folder.parent
    raise SystemExit("Could not find Celbridge.slnx above the skill folder.")


def read_text(path: Path) -> str:
    """Read a text file as UTF-8 or Windows-1252, with LF line endings and no trailing whitespace."""
    data = path.read_bytes()
    try:
        text = data.decode("utf-8-sig")
    except UnicodeDecodeError:
        text = data.decode("cp1252")
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [line.rstrip() for line in text.split("\n")]
    return "\n".join(lines).strip("\n")


def as_list(value) -> list[str]:
    """Return a manifest value that may be a string or a list of strings as a list."""
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def version_sort_key(version: str) -> list[tuple]:
    """Order versions numerically part by part, comparing any text part as text."""
    key = []
    for part in re.split(r"[.-]", version):
        if part.isdigit():
            key.append((0, int(part), ""))
        else:
            key.append((1, 0, part))
    return key


def license_identifiers(expression: str) -> list[str]:
    """Return the license identifiers in an SPDX expression, leaving out operators and exceptions."""
    identifiers = []
    skip_exception = False
    for token in re.findall(r"[A-Za-z0-9.+-]+", expression):
        if skip_exception:
            skip_exception = False
            continue
        if token == "WITH":
            skip_exception = True
            continue
        if token in EXPRESSION_OPERATORS:
            continue
        identifiers.append(token)
    return identifiers


def canonical_text_path(identifier: str) -> Path:
    """Return the license-texts file for an SPDX identifier, ignoring -only, -or-later and + suffixes."""
    base_identifier = re.sub(r"(-only|-or-later|\+)$", "", identifier)
    return LICENSE_TEXTS_FOLDER / f"{base_identifier}.txt"


def describe_license(expression: str) -> str:
    """Return a license expression with each LicenseRef identifier written as plain words."""
    def plain_words(match):
        return match.group(1).replace("-", " ")

    return LICENSE_REFERENCE_PATTERN.sub(plain_words, expression)


def is_covered(relative_path: str, covering_paths: list[str]) -> bool:
    """Return whether a repository path is one of the covering paths, inside one, or contains one."""
    for covering_path in covering_paths:
        if relative_path == covering_path:
            return True
        if relative_path.startswith(covering_path + "/"):
            return True
        if covering_path.startswith(relative_path + "/"):
            return True
    return False


def read_nuspec(package_folder: Path) -> PackageMetadata:
    """Read the notice fields from the nuspec in a package folder of the NuGet cache."""
    nuspec_paths = sorted(package_folder.glob("*.nuspec"))
    if not nuspec_paths:
        return PackageMetadata()

    root = ElementTree.fromstring(nuspec_paths[0].read_bytes())
    metadata = root.find("{*}metadata")
    license_element = metadata.find("{*}license")
    repository_element = metadata.find("{*}repository")

    result = PackageMetadata()
    result.authors = (metadata.findtext("{*}authors") or "").strip().strip("'\"")
    result.copyright = (metadata.findtext("{*}copyright") or "").strip()
    if license_element is not None:
        result.license_type = license_element.get("type", "")
        result.license = (license_element.text or "").strip()
    result.license_url = (metadata.findtext("{*}licenseUrl") or "").strip()
    result.project_url = (metadata.findtext("{*}projectUrl") or "").strip()
    if repository_element is not None:
        result.repository_url = repository_element.get("url", "").removesuffix(".git")
    return result


def has_shipped_files(package_details: dict) -> bool:
    """Return whether a restore target entry puts any file into the build output."""
    for key in SHIPPED_ASSET_KEYS:
        for asset_path in package_details.get(key) or {}:
            if not asset_path.endswith("/_._"):
                return True
    return False


def collect_shipped_packages(assets: dict) -> dict[str, dict[str, Path]]:
    """Map each package with shipped files to its versions and their folders in the NuGet cache."""
    packages_folder = Path(assets["project"]["restore"]["packagesPath"])
    shipped = {}
    for target_name, target_packages in assets["targets"].items():
        framework = target_name.split("/")[0]
        # The platform-specific frameworks are the app heads. The plain framework is not shipped.
        if "-" not in framework:
            continue
        for name_and_version, package_details in target_packages.items():
            if package_details.get("type") != "package":
                continue
            if not has_shipped_files(package_details):
                continue
            name, version = name_and_version.split("/")
            versions = shipped.setdefault(name, {})
            versions[version] = packages_folder / name.lower() / version.lower()
    return shipped


def collect_graph_package_ids(assets: dict) -> list[str]:
    """Return the id of every package in the restore graph, shipped or not."""
    package_ids = set()
    for library_key, library in assets["libraries"].items():
        if library.get("type") == "package":
            package_ids.add(library_key.split("/")[0])
    return sorted(package_ids)


def find_decision(package_id: str, decisions: list[dict]) -> dict:
    """Return the fields of every manifest package decision matching a package, the earliest decision winning each field."""
    merged = {}
    for decision in decisions:
        patterns = as_list(decision.get("ids"))
        matches = [pattern for pattern in patterns if fnmatch.fnmatch(package_id.lower(), pattern.lower())]
        if not matches:
            continue
        for key, value in decision.items():
            merged.setdefault(key, value)
    return merged


def find_notices_texts(package_folders: list[Path]) -> list[str]:
    """Return the distinct third-party notices files at the root of the given package folders."""
    texts = {}
    for package_folder in package_folders:
        if not package_folder.is_dir():
            continue
        for path in sorted(package_folder.iterdir()):
            if path.is_file() and NOTICES_FILE_PATTERN.match(path.name):
                text = read_text(path)
                texts[hashlib.sha256(text.encode("utf-8")).hexdigest()] = text
    return list(texts.values())


def check_license_texts(subject: str, identifiers: list[str], has_own_text: bool, issues: list[Issue]):
    """Report each SPDX identifier that has no text in license-texts and is not covered by its own file."""
    for identifier in identifiers:
        if identifier.startswith("LicenseRef-"):
            continue
        if canonical_text_path(identifier).exists():
            continue
        if has_own_text:
            continue
        issues.append(Issue(subject, f"no license text for {identifier}. Add license-texts/{canonical_text_path(identifier).name}"))


def build_package_entries(assets: dict, manifest: dict, issues: list[Issue]) -> list[Entry]:
    """Build the entries for the shipped NuGet packages, applying the manifest's package decisions."""
    decisions = manifest.get("package", [])
    accepted_licenses = set(manifest.get("accepted_licenses", []))
    shipped = collect_shipped_packages(assets)

    entries = []
    for package_id in sorted(shipped, key=str.lower):
        decision = find_decision(package_id, decisions)
        if decision.get("exclude"):
            continue

        versions = sorted(shipped[package_id], key=version_sort_key)
        package_folders = [shipped[package_id][version] for version in versions]
        newest_folder = package_folders[-1]
        metadata = read_nuspec(newest_folder)

        license_file_text = ""
        if metadata.license_type == "file":
            license_file_text = read_text(newest_folder / metadata.license)

        license_expression = decision.get("license", "")
        if not license_expression and metadata.license_type == "expression":
            license_expression = metadata.license
        if not license_expression and not license_file_text:
            url_match = NUGET_LICENSE_URL_PATTERN.match(metadata.license_url)
            if url_match:
                license_expression = url_match.group(1)

        if not license_expression and not license_file_text:
            if metadata.license_url:
                message = f"no license expression, only the license URL {metadata.license_url}"
            else:
                message = "no license information in the package metadata"
            issues.append(Issue(package_id, message))

        identifiers = license_identifiers(license_expression)
        unaccepted = [identifier for identifier in identifiers if identifier not in accepted_licenses]
        if license_file_text and not license_expression:
            unaccepted.append("a custom license file")
        if unaccepted and not decision.get("accept_license"):
            issues.append(Issue(package_id, f"license {', '.join(unaccepted)} is not in accepted_licenses"))
        check_license_texts(package_id, identifiers, bool(license_file_text), issues)

        notices_texts = find_notices_texts(package_folders)
        notices_choice = decision.get("notices")
        if notices_texts and notices_choice not in ("include", "omit"):
            issues.append(Issue(package_id, 'ships a third-party notices file. Set notices = "include" or "omit"'))
        if notices_choice != "include":
            notices_texts = []

        copyright_lines = as_list(decision.get("copyright"))
        if not copyright_lines and metadata.copyright:
            copyright_lines = [metadata.copyright]
        if not copyright_lines and metadata.authors:
            copyright_lines = [f"Authors: {metadata.authors}"]

        source = decision.get("source") or metadata.project_url or metadata.repository_url
        if not source:
            source = f"https://www.nuget.org/packages/{package_id}"

        entries.append(Entry(
            name=package_id,
            versions=versions,
            license_expression=license_expression,
            source=source,
            copyright_lines=copyright_lines,
            note=decision.get("note", ""),
            license_file_text=license_file_text,
            notices_texts=notices_texts,
        ))
    return entries


def resolve_runtime_pack(assets: dict, pack_id: str, subject: str, issues: list[Issue]) -> tuple[str, str]:
    """Return the newest cached runtime pack version for the app's .NET version, and its notices text."""
    framework_versions = []
    for target_name in assets["targets"]:
        match = re.match(r"^net(\d+\.\d+)-", target_name)
        if match:
            framework_versions.append(match.group(1))
    if not framework_versions:
        issues.append(Issue(subject, "could not work out the app's .NET version from the restore output"))
        return "", ""

    dotnet_version = max(framework_versions, key=version_sort_key)
    pack_folder = Path(assets["project"]["restore"]["packagesPath"]) / pack_id
    versions = []
    if pack_folder.is_dir():
        versions = [path.name for path in pack_folder.iterdir() if path.name.startswith(dotnet_version + ".")]
    if not versions:
        issues.append(Issue(subject, f"no {pack_id} {dotnet_version}.x in the NuGet cache. Restore the application project"))
        return "", ""

    newest_version = max(versions, key=version_sort_key)
    notices_texts = find_notices_texts([pack_folder / newest_version])
    notices_text = ""
    if notices_texts:
        notices_text = notices_texts[0]
    return newest_version, notices_text


def check_component_version(repository_root: Path, component: dict, issues: list[Issue], warnings: list[str]):
    """Compare a component's manifest version with the version found in the repository."""
    version_check = component.get("version_check")
    if not version_check:
        return

    name = component["name"]
    matches = sorted(repository_root.glob(version_check["file"]))
    if not matches:
        warnings.append(f"{name}: no file matches the version_check file {version_check['file']}")
        return

    match = re.search(version_check["pattern"], read_text(matches[-1]))
    if not match:
        warnings.append(f"{name}: the version_check pattern found nothing in {matches[-1].relative_to(repository_root).as_posix()}")
        return

    found_version = match.group(1)
    if found_version != component.get("version"):
        issues.append(Issue(name, f"the manifest says version {component.get('version')} but the repository has {found_version}"))


def build_component_entries(repository_root: Path, assets: dict, manifest: dict, issues: list[Issue], warnings: list[str]) -> list[Entry]:
    """Build the entries for the bundled components recorded in the manifest."""
    entries = []
    for component in manifest.get("component", []):
        name = component["name"]
        version = component.get("version", "")

        for relative_path in as_list(component.get("paths")):
            if (repository_root / relative_path).exists():
                continue
            if component.get("generated"):
                warnings.append(f"{name}: {relative_path} does not exist yet. It is created by a build or install step")
            else:
                issues.append(Issue(name, f"the path {relative_path} does not exist"))

        check_component_version(repository_root, component, issues, warnings)

        notices_texts = []
        for relative_path in as_list(component.get("notices_file")):
            notices_texts.append(read_text(repository_root / relative_path))

        runtime_pack = component.get("runtime_pack")
        if runtime_pack:
            version, runtime_notices_text = resolve_runtime_pack(assets, runtime_pack, name, issues)
            if runtime_notices_text:
                notices_texts.append(runtime_notices_text)

        license_file_text = ""
        if component.get("license_file"):
            license_file_text = read_text(repository_root / component["license_file"])

        license_expression = component["license"]
        check_license_texts(name, license_identifiers(license_expression), bool(license_file_text), issues)

        versions = []
        if version:
            versions = [version]

        entries.append(Entry(
            name=name,
            versions=versions,
            license_expression=license_expression,
            source=component["source"],
            copyright_lines=as_list(component.get("copyright")),
            note=component.get("note", ""),
            license_file_text=license_file_text,
            notices_texts=notices_texts,
        ))
    return sorted(entries, key=lambda entry: entry.name.lower())


def check_stale_decisions(assets: dict, manifest: dict, issues: list[Issue]):
    """Report manifest package decision ids that no longer match any package in the restore graph."""
    graph_package_ids = [package_id.lower() for package_id in collect_graph_package_ids(assets)]
    for decision in manifest.get("package", []):
        for pattern in as_list(decision.get("ids")):
            if not fnmatch.filter(graph_package_ids, pattern.lower()):
                issues.append(Issue(pattern, "a manifest package decision matches no package in the restore graph. Remove it"))


def discover_vendored_paths(repository_root: Path) -> list[str]:
    """Return the folders under Source that hold vendored bundles, fonts or third-party license files."""
    found = set()
    source_folder = repository_root / "Source"
    for folder, subfolder_names, file_names in os.walk(source_folder):
        subfolder_names[:] = [name for name in subfolder_names if name not in SKIPPED_FOLDER_NAMES]
        relative_folder = Path(folder).relative_to(repository_root).as_posix()
        if Path(folder).name in VENDORED_FOLDER_NAMES:
            found.add(relative_folder)
            subfolder_names[:] = []
            continue
        for file_name in file_names:
            is_font = Path(file_name).suffix.lower() in FONT_EXTENSIONS
            is_license = LICENSE_FILE_PATTERN.match(file_name) is not None
            is_minified = file_name.endswith((".min.js", ".min.css"))
            if is_font or is_license or is_minified:
                found.add(relative_folder)
                break
    return sorted(found)


def check_vendored_paths(repository_root: Path, manifest: dict, issues: list[Issue]):
    """Report vendored-looking folders that no component or ignored path in the manifest covers."""
    covering_paths = []
    for component in manifest.get("component", []):
        covering_paths.extend(as_list(component.get("paths")))
    for ignored in manifest.get("ignored_path", []):
        covering_paths.append(ignored["path"])

    for relative_folder in discover_vendored_paths(repository_root):
        if not is_covered(relative_folder, covering_paths):
            issues.append(Issue(relative_folder, "looks like third-party code but no component or ignored_path covers it"))


def render_entry(entry: Entry) -> list[str]:
    """Return the notice lines for one entry."""
    heading = entry.name
    if entry.versions:
        heading = f"{entry.name} {', '.join(entry.versions)}"

    license_description = describe_license(entry.license_expression)
    if entry.license_file_text:
        if license_description:
            license_description = f"{license_description}, see the license text below"
        else:
            license_description = "custom, see the license text below"

    lines = [
        heading,
        f"    License: {license_description}",
        f"    Source: {entry.source}",
    ]
    for copyright_line in entry.copyright_lines:
        lines.append(f"    {copyright_line}")
    if entry.note:
        lines.append(f"    Note: {entry.note}")
    if entry.notices_texts:
        lines.append("    Notices: reproduced in the notices section below")
    return lines


def render_section_heading(title: str) -> list[str]:
    """Return a top-level section heading."""
    return [
        "=" * 100,
        title,
        "=" * 100,
    ]


def render_text_block(title: str, text: str) -> list[str]:
    """Return a titled block holding a license or notices text."""
    return [
        "-" * 100,
        title,
        "-" * 100,
        "",
        text,
        "",
    ]


def group_texts(entries: list[Entry], texts_of_entry) -> list[tuple[list[str], str]]:
    """Group identical texts, returning the names of the entries sharing each text with the text."""
    groups = {}
    for entry in entries:
        for text in texts_of_entry(entry):
            key = hashlib.sha256(text.encode("utf-8")).hexdigest()
            names, _ = groups.setdefault(key, ([], text))
            if entry.name not in names:
                names.append(entry.name)
    return sorted(groups.values(), key=lambda group: group[0][0].lower())


def render_file(component_entries: list[Entry], package_entries: list[Entry]) -> str:
    """Return the full content of THIRD-PARTY-LICENSES.txt."""
    all_entries = component_entries + package_entries
    lines = [HEADER, ""]

    entry_groups = [
        ("Bundled components", component_entries),
        ("NuGet packages", package_entries),
    ]
    lines.extend(render_section_heading("COMPONENTS"))
    for group_title, entries in entry_groups:
        lines.extend(["", group_title, "-" * len(group_title)])
        for entry in entries:
            lines.append("")
            lines.extend(render_entry(entry))
    lines.append("")

    lines.extend(render_section_heading("LICENSE TEXTS"))
    lines.append("")
    identifiers = set()
    for entry in all_entries:
        for identifier in license_identifiers(entry.license_expression):
            if canonical_text_path(identifier).exists():
                identifiers.add(canonical_text_path(identifier).stem)
    for identifier in sorted(identifiers, key=str.lower):
        lines.extend(render_text_block(identifier, read_text(LICENSE_TEXTS_FOLDER / f"{identifier}.txt")))

    def license_files_of(entry):
        if entry.license_file_text:
            return [entry.license_file_text]
        return []

    for names, text in group_texts(all_entries, license_files_of):
        lines.extend(render_text_block(f"License for {', '.join(names)}", text))

    notices_groups = group_texts(all_entries, lambda entry: entry.notices_texts)
    if notices_groups:
        lines.extend(render_section_heading("NOTICES"))
        lines.append("")
        for names, text in notices_groups:
            lines.extend(render_text_block(f"Notices for {', '.join(names)}", text))

    return "\n".join(lines).rstrip("\n") + "\n"


def print_report(package_entries: list[Entry], component_entries: list[Entry], warnings: list[str], issues: list[Issue]):
    """Print what was found, then any warnings and issues."""
    license_counts = {}
    for entry in package_entries + component_entries:
        for identifier in license_identifiers(entry.license_expression) or ["(license file only)"]:
            license_counts[identifier] = license_counts.get(identifier, 0) + 1

    print(f"NuGet packages: {len(package_entries)}")
    print(f"Bundled components: {len(component_entries)}")
    print("Licenses:")
    for identifier, count in sorted(license_counts.items(), key=lambda item: (-item[1], item[0].lower())):
        print(f"    {count:4d}  {identifier}")

    if warnings:
        print("\nWarnings:")
        for warning in warnings:
            print(f"    {warning}")

    if issues:
        subjects_by_message = {}
        for issue in issues:
            subjects_by_message.setdefault(issue.message, []).append(issue.subject)
        print(f"\nIssues ({len(issues)}):")
        for message, subjects in subjects_by_message.items():
            print(f"    {', '.join(subjects)}: {message}")


def main() -> int:
    """Generate the notices file and return the process exit code."""
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Generate THIRD-PARTY-LICENSES.txt for Celbridge.")
    parser.add_argument("--check", action="store_true", help="report without writing the file")
    arguments = parser.parse_args()

    repository_root = find_repository_root()
    manifest = tomllib.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    assets_path = repository_root / manifest["assets_file"]
    if not assets_path.exists():
        print(f"{assets_path} does not exist. Restore the application project first.")
        return 2
    assets = json.loads(assets_path.read_text(encoding="utf-8"))

    issues = []
    warnings = []
    package_entries = build_package_entries(assets, manifest, issues)
    component_entries = build_component_entries(repository_root, assets, manifest, issues, warnings)
    check_stale_decisions(assets, manifest, issues)
    check_vendored_paths(repository_root, manifest, issues)

    print_report(package_entries, component_entries, warnings, issues)

    if issues:
        print(f"\n{OUTPUT_FILE_NAME} was not written. Resolve the issues and run again.")
        return 1
    if arguments.check:
        print("\nNo issues. Nothing written because --check was given.")
        return 0

    output_path = repository_root / OUTPUT_FILE_NAME
    output_path.write_text(render_file(component_entries, package_entries), encoding="utf-8", newline="\n")
    print(f"\nWrote {output_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
