using System.IO.Compression;
using System.Runtime.Versioning;

namespace Celbridge.Python.Services;

[SupportedOSPlatform("windows10.0.10240.0")]
public static class PythonInstaller
{
    private const string PythonFolderName = "Python";
    private const string PythonAssetsFolder = "Assets\\Python";
    private const string UVZipAssetPath = "ms-appx:///Assets/UV/uv-x86_64-pc-windows-msvc.zip";
    private const string InstalledVersionFileName = "installed_version.txt";
    private const string BuildVersionFileName = "build_version.txt";
    private const string UVTempFileName = "uv.zip";

    /// <summary>
    /// Installs Python support files if needed.
    /// </summary>
    public static async Task<Result<string>> InstallPythonAsync(string appVersion)
    {
        try
        {
            var localFolder = ApplicationData.Current.LocalFolder;
            var pythonFolderPath = Path.Combine(localFolder.Path, PythonFolderName);

            bool needsReinstall = IsInstallRequired(pythonFolderPath, appVersion);

            if (needsReinstall)
            {
                await ReinstallAsync(localFolder, pythonFolderPath, appVersion);
            }

            return Result<string>.Ok(pythonFolderPath);
        }
        catch (Exception ex)
        {
            return Result<string>.Fail($"Failed to install Python support files")
                .WithException(ex);
        }
    }

    private static bool IsInstallRequired(string pythonFolderPath, string currentVersion)
    {
        // If the python folder doesn't exist, we need to install
        if (!Directory.Exists(pythonFolderPath))
        {
            return true;
        }

        var installedVersionPath = Path.Combine(pythonFolderPath, InstalledVersionFileName);

        // If version file doesn't exist, we need to install
        if (!File.Exists(installedVersionPath))
        {
            return true;
        }

        // Read the installed version and compare.
        // The installed version file contains both the app version and the build version
        // (separated by a newline) so that changes to either trigger a reinstall.
        var installedVersionContent = File.ReadAllText(installedVersionPath).Trim();
        var expectedVersionContent = GetVersionContent(currentVersion);

        if (!string.Equals(expectedVersionContent, installedVersionContent, StringComparison.Ordinal))
        {
            return true;
        }

        return false;
    }

    /// <summary>
    /// Builds the version content string that combines the app version and the
    /// Python package build version. This is written to the installed version file
    /// and compared on subsequent runs to detect when either the app or the Python
    /// packages have changed.
    /// </summary>
    private static string GetVersionContent(string appVersion)
    {
        // Read the build version from the Assets folder.
        // This file is generated by build.py with a unique GUID each time the wheels are rebuilt.
        var buildVersion = "";
        try
        {
            var installedLocation = Package.Current.InstalledLocation;
            var buildVersionPath = Path.Combine(installedLocation.Path, PythonAssetsFolder, BuildVersionFileName);
            if (File.Exists(buildVersionPath))
            {
                buildVersion = File.ReadAllText(buildVersionPath).Trim();
            }
        }
        catch
        {
            // Non-critical: if we can't read the build version, the app version
            // alone will still trigger reinstalls on app updates.
        }

        return $"{appVersion}\n{buildVersion}";
    }

    private static async Task ReinstallAsync(StorageFolder localFolder, string pythonFolderPath, string currentVersion)
    {
        // Delete existing folder if it exists (handles upgrade scenario).
        // A clean delete ensures no stale data remains from a previous install.
        // Use retry logic as files may be locked by a previous Python process.
        if (Directory.Exists(pythonFolderPath))
        {
            try
            {
                await DeleteDirectoryWithRetryAsync(pythonFolderPath);
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException(
                    $"Failed to delete existing Python folder '{pythonFolderPath}'. " +
                    "A previous Python process may still be running with locked files. " +
                    "Close all Celbridge instances and try again.",
                    ex);
            }
        }

        var pythonFolder = await localFolder.CreateFolderAsync(PythonFolderName, CreationCollisionOption.OpenIfExists);

        // uv handles installing the required python & package versions for the loaded project
        var uvZipFile = await StorageFile.GetFileFromApplicationUriAsync(new Uri(UVZipAssetPath));
        var uvTempFile = await uvZipFile.CopyAsync(ApplicationData.Current.TemporaryFolder, UVTempFileName, NameCollisionOption.ReplaceExisting);
        ZipFile.ExtractToDirectory(uvTempFile.Path, pythonFolder.Path, overwriteFiles: true);

        // Copy the embedded Python assets to the local Python folder
        StorageFolder installedLocation = Package.Current.InstalledLocation;
        StorageFolder pythonAssetsFolder = await installedLocation.GetFolderAsync(PythonAssetsFolder);
        await CopyStorageFolderAsync(pythonAssetsFolder, pythonFolder.Path);

        // Write the version file after successful install.
        // This signals that the install completed successfully and includes both the app
        // version and the build version so that changes to either trigger a reinstall.
        var versionFile = Path.Combine(pythonFolderPath, InstalledVersionFileName);
        var versionContent = GetVersionContent(currentVersion);
        await File.WriteAllTextAsync(versionFile, versionContent);
    }

    private static async Task CopyStorageFolderAsync(StorageFolder sourceFolder, string destinationPath)
    {
        if (sourceFolder == null)
        {
            throw new ArgumentNullException(nameof(sourceFolder));
        }

        if (string.IsNullOrWhiteSpace(destinationPath))
        {
            throw new ArgumentException("Destination path must not be empty", nameof(destinationPath));
        }

        Directory.CreateDirectory(destinationPath);

        var files = await sourceFolder.GetFilesAsync();
        foreach (var file in files)
        {
            var targetFilePath = Path.Combine(destinationPath, file.Name);
            using (var sourceStream = await file.OpenStreamForReadAsync())
            using (var destinationStream = File.Create(targetFilePath))
            {
                await sourceStream.CopyToAsync(destinationStream);
            }
        }

        var subfolders = await sourceFolder.GetFoldersAsync();
        foreach (var subfolder in subfolders)
        {
            var subfolderPath = Path.Combine(destinationPath, subfolder.Name);
            await CopyStorageFolderAsync(subfolder, subfolderPath);
        }
    }

    /// <summary>
    /// Deletes a directory with retry logic to handle locked files.
    /// Files may be locked by a previous Python process that hasn't fully exited yet.
    /// </summary>
    private static async Task DeleteDirectoryWithRetryAsync(string directoryPath, int maxRetries = 5, int delayMs = 500)
    {
        for (int attempt = 1; attempt <= maxRetries; attempt++)
        {
            try
            {
                Directory.Delete(directoryPath, recursive: true);
                return;
            }
            catch (UnauthorizedAccessException) when (attempt < maxRetries)
            {
                // Files may be locked - wait and retry
                await Task.Delay(delayMs * attempt);
            }
            catch (IOException) when (attempt < maxRetries)
            {
                // Files may be in use - wait and retry
                await Task.Delay(delayMs * attempt);
            }
        }

        // Final attempt without catching - let it throw if it fails
        Directory.Delete(directoryPath, recursive: true);
    }
}
