[document]
id = "doc-document"
type = "custom"
entry_point = "index.html"
priority = "default"

[[document_file_types]]
extension = ".doc"
display_name = "Note_FileType_Note"

[[document_templates]]
id = "empty"
display_name = "Note_Template_Empty"
file = "templates/empty.doc"
default = true
