using System.Text.RegularExpressions;
using Celbridge.Python.Services;
using Celbridge.Utilities;

namespace Celbridge.Console.Helpers;

/// <summary>
/// One generated start-up file: its path under the console folder, and its content.
/// </summary>
public sealed record ConsoleStartupFile(string RelativePath, string Content);

/// <summary>
/// Supplies the start-up files for a console's shell. Each shell has one set of files, used whether the shell
/// profile is on or off.
/// When the shell profile is on, the files run the user's own start-up files. Just before the first prompt, they
/// restore Celbridge's settings. When the profile is off, only the system's start-up files run. When the compact
/// prompt is on, the files also set a short prompt before every prompt.
/// The scripts are embedded from the StartupScripts folder. The only values filled into them are the uv and
/// Python filter's lists. Every other value, including both settings, comes from variables Celbridge sets when it
/// starts the shell. This keeps the user's environment off disk, and lets every console share the same files. The
/// scripts name those variables directly, so each name here must match the scripts.
/// </summary>
public static class ConsoleStartupFiles
{
    /// <summary>
    /// Lists the variables the start-up restores after the user's files have run.
    /// </summary>
    public const string RestoreVariable = "CELBRIDGE_CONSOLE_RESTORE";

    /// <summary>
    /// Holds the path of the shell's history file.
    /// </summary>
    public const string HistoryVariable = "CELBRIDGE_CONSOLE_HISTORY";

    /// <summary>
    /// Holds the folder where zsh would normally find the user's own start-up files.
    /// </summary>
    public const string UserZdotdirVariable = "CELBRIDGE_CONSOLE_USER_ZDOTDIR";

    /// <summary>
    /// Holds the console's command, with the executable and each argument on a line of its own. The start-up
    /// splits the value only at line breaks, so arguments need no shell quoting. It is unset when the console
    /// has no command.
    /// </summary>
    public const string CommandVariable = "CELBRIDGE_CONSOLE_COMMAND";

    /// <summary>
    /// Holds the folder where the console's command runs.
    /// </summary>
    public const string WorkingFolderVariable = "CELBRIDGE_CONSOLE_WORKING_FOLDER";

    /// <summary>
    /// When this variable is set, the user's own start-up files run.
    /// </summary>
    public const string UseShellProfileVariable = "CELBRIDGE_CONSOLE_USE_SHELL_PROFILE";

    /// <summary>
    /// When this variable is set, the start-up uses the compact prompt.
    /// </summary>
    public const string CompactPromptVariable = "CELBRIDGE_CONSOLE_COMPACT_PROMPT";

    /// <summary>
    /// The prefix of the variables that only the start-up uses. The start-up removes them when it finishes.
    /// </summary>
    public const string VariablePrefix = "CELBRIDGE_CONSOLE_";

    public const string ZshFolder = "zsh";
    public const string BashRcFile = "bash/bashrc";
    public const string PowerShellFile = "powershell/startup.ps1";

    private const string Header = "Generated by Celbridge when a console starts. Changes made here are overwritten.";

    private const string ScriptResourcePrefix = "Celbridge.Console.StartupScripts.";

    // The tokens in the scripts that are replaced with the uv and Python filter's lists.
    private const string KeptPatternsToken = "{{KEPT_PATTERNS}}";
    private const string RemovedPatternsToken = "{{REMOVED_PATTERNS}}";
    private const string CommandNamesToken = "{{COMMAND_NAMES}}";

    // Each zsh script, and the file it is written to. zsh reads these files from ZDOTDIR in this order. It reads
    // .zshenv on every start, and the others only in a login shell.
    private static readonly (string Script, string RelativePath)[] ZshScripts =
    {
        ("zshenv.zsh", $"{ZshFolder}/.zshenv"),
        ("zprofile.zsh", $"{ZshFolder}/.zprofile"),
        ("zshrc.zsh", $"{ZshFolder}/.zshrc"),
        ("zlogin.zsh", $"{ZshFolder}/.zlogin"),
    };

    private const string BashScript = "bashrc.bash";
    private const string PowerShellScript = "startup.ps1";

    // A valid POSIX shell variable name.
    private static readonly Regex ShellVariableNamePattern = new("^[A-Za-z_][A-Za-z0-9_]*$", RegexOptions.Compiled);

    /// <summary>
    /// The value of the restore variable: the names of the variables the start-up restores after the user's files
    /// run. These are the variables the session sets. PATH is included only when the console sets its own PATH.
    /// Otherwise the start-up just moves Celbridge's folders to the front of PATH. Names that are not valid shell
    /// variables are left out, because no profile can change them.
    /// </summary>
    public static string BuildRestoreList(IEnumerable<string> sessionVariableNames, bool restoresPath)
    {
        var names = sessionVariableNames
            .Where(name => restoresPath || !EnvironmentVariableNames.IsPath(name))
            .Where(name => !name.StartsWith(VariablePrefix, StringComparison.Ordinal))
            .Where(name => ShellVariableNamePattern.IsMatch(name))
            .OrderBy(name => name, StringComparer.Ordinal);

        return string.Join(' ', names);
    }

    /// <summary>
    /// Returns the start-up files for the shell. The list is empty for a shell that has no start-up files.
    /// </summary>
    public static IReadOnlyList<ConsoleStartupFile> Generate(ConsoleShell shell)
    {
        if (shell.IsZsh)
        {
            return ZshScripts
                .Select(zshScript => new ConsoleStartupFile(zshScript.RelativePath, BuildPosixScript(zshScript.Script)))
                .ToList();
        }

        if (shell.IsBash)
        {
            return new[] { new ConsoleStartupFile(BashRcFile, BuildPosixScript(BashScript)) };
        }

        if (shell.Family == ConsoleShellFamily.PowerShell)
        {
            return new[] { new ConsoleStartupFile(PowerShellFile, BuildPowerShellStartup()) };
        }

        return Array.Empty<ConsoleStartupFile>();
    }

    /// <summary>
    /// The PowerShell start-up script. The console passes it on PowerShell's command line, not as a script file,
    /// because an execution policy can block an unsigned script.
    /// </summary>
    public static string BuildPowerShellStartup()
    {
        var script = ReadScript(PowerShellScript)
            .Replace(KeptPatternsToken, PowerShellList(KeptPatterns()))
            .Replace(RemovedPatternsToken, PowerShellList(RemovedPatterns()))
            .Replace(CommandNamesToken, PowerShellList(PythonEnvironmentFilter.CommandNames));

        return $"# {Header}\n\n{script}";
    }

    // A zsh or bash script. Each pattern list becomes a case pattern, and the command names a list of words.
    private static string BuildPosixScript(string scriptName)
    {
        var script = ReadScript(scriptName)
            .Replace(KeptPatternsToken, string.Join('|', KeptPatterns()))
            .Replace(RemovedPatternsToken, string.Join('|', RemovedPatterns()))
            .Replace(CommandNamesToken, string.Join(' ', PythonEnvironmentFilter.CommandNames));

        return $"# {Header}\n\n{script}";
    }

    // An editor can save a script with CRLF line endings, which bash and zsh cannot run, so they are made LF here.
    private static string ReadScript(string scriptName)
    {
        var assembly = typeof(ConsoleStartupFiles).Assembly;
        var readResult = EmbeddedResourceReader.ReadText(assembly, ScriptResourcePrefix + scriptName);
        if (readResult.IsFailure)
        {
            throw new InvalidOperationException(readResult.FirstErrorMessage);
        }

        return readResult.Value.ReplaceLineEndings("\n");
    }

    // The variables the restore keeps, as patterns: each name, and each prefix followed by *.
    private static IEnumerable<string> KeptPatterns()
    {
        return PythonEnvironmentFilter.KeptNames
            .Concat(PythonEnvironmentFilter.KeptPrefixes.Select(prefix => prefix + "*"));
    }

    // The variables the restore removes, unless they are kept, as patterns.
    private static IEnumerable<string> RemovedPatterns()
    {
        return PythonEnvironmentFilter.RemovedNames
            .Concat(PythonEnvironmentFilter.RemovedPrefixes.Select(prefix => prefix + "*"));
    }

    private static string PowerShellList(IEnumerable<string> values)
    {
        return string.Join(", ", values.Select(value => $"'{value}'"));
    }
}
