using Celbridge.Python.Services;

namespace Celbridge.Console.Helpers;

/// <summary>
/// One generated start-up file: its path under the console folder, and its content.
/// </summary>
public sealed record ConsoleStartupFile(string RelativePath, string Content);

/// <summary>
/// Generates the start-up files for a console's shell. Each shell has one set of files, used whether the shell
/// profile is on or off.
/// When the shell profile is on, the files run the user's own start-up files. Just before the first prompt, they
/// restore Celbridge's settings. When the profile is off, only the system's start-up files run. When the compact
/// prompt is on, the files also set a short prompt before every prompt.
/// The files contain no values. Every value, including both settings, comes from variables Celbridge sets when it
/// starts the shell. This keeps the user's environment off disk, and lets every console share the same files.
/// </summary>
public static class ConsoleStartupFiles
{
    /// <summary>
    /// Lists the variables the start-up restores after the user's files have run.
    /// </summary>
    public const string RestoreVariable = "CELBRIDGE_CONSOLE_RESTORE";

    /// <summary>
    /// Holds the path of the shell's history file.
    /// </summary>
    public const string HistoryVariable = "CELBRIDGE_CONSOLE_HISTORY";

    /// <summary>
    /// Holds the folder where zsh would normally find the user's own start-up files.
    /// </summary>
    public const string UserZdotdirVariable = "CELBRIDGE_CONSOLE_USER_ZDOTDIR";

    /// <summary>
    /// Holds the console's command, with the executable and each argument on a line of its own. The start-up
    /// splits the value only at line breaks, so arguments need no shell quoting. It is unset when the console
    /// has no command.
    /// </summary>
    public const string CommandVariable = "CELBRIDGE_CONSOLE_COMMAND";

    /// <summary>
    /// Holds the folder where the console's command runs.
    /// </summary>
    public const string WorkingFolderVariable = "CELBRIDGE_CONSOLE_WORKING_FOLDER";

    /// <summary>
    /// When this variable is set, the user's own start-up files run.
    /// </summary>
    public const string UseShellProfileVariable = "CELBRIDGE_CONSOLE_USE_SHELL_PROFILE";

    /// <summary>
    /// When this variable is set, the start-up uses the compact prompt.
    /// </summary>
    public const string CompactPromptVariable = "CELBRIDGE_CONSOLE_COMPACT_PROMPT";

    /// <summary>
    /// The prefix of the variables that only the start-up uses. The start-up removes them when it finishes.
    /// </summary>
    public const string VariablePrefix = "CELBRIDGE_CONSOLE_";

    public const string ZshFolder = "zsh";
    public const string BashRcFile = "bash/bashrc";
    public const string PowerShellFile = "powershell/startup.ps1";

    private const string Header = "Generated by Celbridge when a console starts. Changes made here are overwritten.";

    // The compact prompts: the working folder's name in cyan, then the shell's usual prompt character.
    private const string ZshCompactPrompt = "%F{cyan}%1~%f %# ";
    private const string BashCompactPrompt = @"\[\e[36m\]\W\[\e[m\] \$ ";

    // zsh reads these files from ZDOTDIR in this order. It reads .zshenv on every start, and the others only in
    // a login shell.
    private static readonly string[] ZshFileNames =
    {
        ".zshenv",
        ".zprofile",
        ".zshrc",
        ".zlogin",
    };

    /// <summary>
    /// Returns the start-up files for the shell. The list is empty for a shell that has no start-up files.
    /// </summary>
    public static IReadOnlyList<ConsoleStartupFile> Generate(ConsoleShell shell)
    {
        var files = new List<ConsoleStartupFile>();

        if (shell.IsZsh)
        {
            foreach (var fileName in ZshFileNames)
            {
                var content = BuildZshFile(fileName);
                files.Add(new ConsoleStartupFile($"{ZshFolder}/{fileName}", content));
            }
        }
        else if (shell.IsBash)
        {
            files.Add(new ConsoleStartupFile(BashRcFile, BuildBashRc()));
        }
        else if (shell.Family == ConsoleShellFamily.PowerShell)
        {
            files.Add(new ConsoleStartupFile(PowerShellFile, BuildPowerShellStartup()));
        }

        return files;
    }

    /// <summary>
    /// The PowerShell start-up script. The console passes it on PowerShell's command line, not as a script file,
    /// because an execution policy can block an unsigned script.
    /// </summary>
    public static string BuildPowerShellStartup()
    {
        return $$"""
            # {{Header}}
            # PowerShell receives this script on its command line. This copy on disk is only for reference.

            # Save Celbridge's values and the start-up settings before any profile runs. Then remove the start-up
            # variables, so the profiles and the console's command never see them.
            $global:CelbridgeSnapshot = @{}
            foreach ($celbridgeName in ("$env:{{RestoreVariable}}" -split ' ' | Where-Object { $_ })) {
                $global:CelbridgeSnapshot[$celbridgeName] = [Environment]::GetEnvironmentVariable($celbridgeName)
            }
            $global:CelbridgeStartup = @{
                PathFolders = @("$env:{{ConsoleEnvironmentVariables.PathFolders}}" -split ';' | Where-Object { $_ })
                UseShellProfile = [bool]$env:{{UseShellProfileVariable}}
                CompactPrompt = [bool]$env:{{CompactPromptVariable}}
                History = $env:{{HistoryVariable}}
                WorkingFolder = $env:{{WorkingFolderVariable}}
                Command = @(if ($env:{{CommandVariable}}) { $env:{{CommandVariable}} -split "`n" })
            }
            foreach ($celbridgeVariable in @(Get-ChildItem Env: | Where-Object { $_.Name -like '{{VariablePrefix}}*' })) {
                Remove-Item -LiteralPath "Env:$($celbridgeVariable.Name)"
            }

            # When the shell profile is on, load the profiles in PowerShell's usual order. If one fails, report the
            # error and keep loading the rest, as PowerShell does.
            if ($global:CelbridgeStartup.UseShellProfile) {
                foreach ($celbridgeProfile in @($PROFILE.AllUsersAllHosts, $PROFILE.AllUsersCurrentHost, $PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)) {
                    if ($celbridgeProfile -and (Test-Path -LiteralPath $celbridgeProfile)) {
                        try {
                            . $celbridgeProfile
                        }
                        catch {
                            Write-Error $_
                        }
                    }
                }
            }

            if ($global:CelbridgeStartup.History -and (Get-Command Set-PSReadLineOption -ErrorAction SilentlyContinue)) {
                Set-PSReadLineOption -HistorySavePath $global:CelbridgeStartup.History
            }

            # Choose the prompt for every prompt after the first. The compact prompt shows only the folder's name,
            # not the full path. When it is off, keep the prompt the profiles set.
            $global:CelbridgePrompt = $function:prompt
            if ($global:CelbridgeStartup.CompactPrompt) {
                $global:CelbridgePrompt = {
                    $celbridgePath = $executionContext.SessionState.Path.CurrentLocation.Path
                    $celbridgeFolder = if ($celbridgePath -eq $HOME) { '~' } else { Split-Path -Leaf $celbridgePath }
                    if (-not $celbridgeFolder) {
                        $celbridgeFolder = $celbridgePath
                    }
                    "PS $celbridgeFolder$('>' * ($nestedPromptLevel + 1)) "
                }
            }

            # Restores Celbridge's settings. Removes the uv and Python settings the profiles added, puts back the
            # saved values, and moves Celbridge's folders to the front of PATH. Also removes any alias or function
            # that hides one of Celbridge's commands.
            function global:CelbridgeRestore {
                foreach ($celbridgeVariable in @(Get-ChildItem Env:)) {
                    $celbridgeName = $celbridgeVariable.Name
                    if ({{PowerShellMatch(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) {
                        continue
                    }
                    if ({{PowerShellMatch(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) {
                        Remove-Item -LiteralPath "Env:$celbridgeName"
                    }
                }

                foreach ($celbridgeEntry in $global:CelbridgeSnapshot.GetEnumerator()) {
                    Set-Item -LiteralPath "Env:$($celbridgeEntry.Key)" -Value $celbridgeEntry.Value
                }

                $celbridgeFolders = $global:CelbridgeStartup.PathFolders
                $celbridgeRest = @("$env:Path" -split ';' | Where-Object { $_ -and $celbridgeFolders -notcontains $_ })
                $env:Path = ($celbridgeFolders + $celbridgeRest) -join ';'

                foreach ($celbridgeCommand in @({{PowerShellList(PythonEnvironmentFilter.CommandNames)}})) {
                    foreach ($celbridgeDrive in @('Alias', 'Function')) {
                        # A command can be defined in several scopes. Each removal deletes only the nearest one.
                        for ($celbridgeAttempt = 0; $celbridgeAttempt -lt 3; $celbridgeAttempt++) {
                            if (-not (Test-Path -LiteralPath "$($celbridgeDrive):$celbridgeCommand")) {
                                break
                            }
                            Remove-Item -LiteralPath "$($celbridgeDrive):$celbridgeCommand" -Force -ErrorAction SilentlyContinue
                        }
                    }
                }
            }

            # Restore the settings again at the first prompt, after the prompt function runs, because a tool's
            # prompt hook can change the environment. Then remove everything the start-up defined.
            function global:prompt {
                $celbridgePrompt = $global:CelbridgePrompt
                $celbridgeText = & $celbridgePrompt
                CelbridgeRestore
                Remove-Item -LiteralPath Function:CelbridgeRestore
                Remove-Variable -Name celbridge* -Scope Global -ErrorAction SilentlyContinue
                $function:global:prompt = $celbridgePrompt
                $celbridgeText
            }

            # Go back to the working folder, since a profile may have changed it. Do this before the restore, so the
            # restore undoes anything a folder change set up.
            # The console becomes visible at the marker. The command runs last, as it would with -NoExit -Command.
            if ($global:CelbridgeStartup.WorkingFolder) {
                Set-Location -LiteralPath $global:CelbridgeStartup.WorkingFolder
            }
            CelbridgeRestore
            if ($global:CelbridgeStartup.Command.Count -gt 0) {
                Clear-Host
                Write-Host -NoNewline ([char]0x{{(int)ConsoleReadyMarker.PowerShellCharacter:x4}})
                $celbridgeExecutable = $global:CelbridgeStartup.Command[0]
                $celbridgeArguments = @($global:CelbridgeStartup.Command | Select-Object -Skip 1)
                & $celbridgeExecutable @celbridgeArguments
            }
            """;
    }

    private static string BuildZshFile(string fileName)
    {
        var lines = new List<string>
        {
            $"# {Header}",
            string.Empty,
        };

        if (fileName == ".zshenv")
        {
            lines.Add(ZshSnapshot);
        }

        lines.Add(ZshSourceUserFile(fileName));

        if (fileName == ".zshenv")
        {
            // Registered in .zshenv because the user's .zshenv can stop zsh reading the later files. The settings
            // must still be restored when that happens.
            lines.Add(BuildZshFirstPrompt());
            lines.Add("precmd_functions+=(_celbridge_first_prompt)");
            lines.Add(ZshCompactPromptHook);
        }

        if (fileName == ".zlogin")
        {
            lines.Add(ZshLastFile);
        }

        return string.Join('\n', lines) + '\n';
    }

    private const string ZshSnapshot = """
        # zsh reads this file first. Save Celbridge's values before any of the user's files can change them.
        typeset -gA _celbridge_snapshot
        for _celbridge_name in ${=CELBRIDGE_CONSOLE_RESTORE}; do
            _celbridge_snapshot[$_celbridge_name]=${(P)_celbridge_name}
        done
        unset _celbridge_name
        _celbridge_zdotdir=$ZDOTDIR
        _celbridge_user_zdotdir=${CELBRIDGE_CONSOLE_USER_ZDOTDIR:-$HOME}

        """;

    // Runs the user's file when the shell profile is on. The file runs at the top level, not in a function, so its
    // typeset declarations stay global. ZDOTDIR points at the user's folder while it runs, as in a terminal.
    // If the user's .zshenv changes ZDOTDIR, their later files are read from the new folder.
    private static string ZshSourceUserFile(string fileName)
    {
        return $$"""
            if [[ -n ${{UseShellProfileVariable}} ]]; then
                ZDOTDIR=$_celbridge_user_zdotdir
                if [[ -r $ZDOTDIR/{{fileName}} ]]; then
                    source $ZDOTDIR/{{fileName}}
                fi
                _celbridge_user_zdotdir=$ZDOTDIR
                ZDOTDIR=$_celbridge_zdotdir
            fi

            """;
    }

    private const string ZshLastFile = """
        # Move Celbridge's hooks to the end, so they run after any hooks the user's files added.
        precmd_functions=(${precmd_functions:#_celbridge_first_prompt} _celbridge_first_prompt)
        if (( ${precmd_functions[(I)_celbridge_compact_prompt]} )); then
            precmd_functions=(${precmd_functions:#_celbridge_compact_prompt} _celbridge_compact_prompt)
        fi

        # zsh loads the history after its start-up files run, so this history file wins over the user's. Each
        # command is written as it is entered, because closing a console kills the shell before it can save.
        if [[ -n $CELBRIDGE_CONSOLE_HISTORY ]]; then
            HISTFILE=$CELBRIDGE_CONSOLE_HISTORY
            if (( ! SAVEHIST )); then
                SAVEHIST=1000
            fi
            if (( HISTSIZE < SAVEHIST )); then
                HISTSIZE=$SAVEHIST
            fi
            setopt INC_APPEND_HISTORY
        fi
        """;

    // Set before every prompt, because a prompt framework may rebuild its prompt before each one. The right-hand
    // prompt is cleared too, so nothing of the old prompt is left.
    private const string ZshCompactPromptHook = $$"""
        if [[ -n $CELBRIDGE_CONSOLE_COMPACT_PROMPT ]]; then
            _celbridge_compact_prompt() {
                PROMPT='{{ZshCompactPrompt}}'
                RPROMPT=
            }
            precmd_functions+=(_celbridge_compact_prompt)
        fi

        """;

    private static string BuildZshFirstPrompt()
    {
        return $$"""
            # Runs once, just before the first prompt. Removes the uv and Python settings the user's files added,
            # and restores Celbridge's. Then shows the console and runs its command.
            _celbridge_first_prompt() {
                precmd_functions=(${precmd_functions:#_celbridge_first_prompt})

                # Go back to the working folder, since a user's file may have changed it. Do this first, so the
                # restore below undoes anything a folder change set up. -q skips the user's folder-change hooks.
                local -a _celbridge_command
                if [[ -n ${{CommandVariable}} ]]; then
                    _celbridge_command=("${(@f){{CommandVariable}}}")
                fi
                if [[ -n ${{WorkingFolderVariable}} ]]; then
                    builtin cd -q -- ${{WorkingFolderVariable}}
                fi

                local _celbridge_name
                for _celbridge_name in ${(k)parameters}; do
                    case $_celbridge_name in
                        ({{ShellPattern(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) ;;
                        ({{ShellPattern(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) unset $_celbridge_name ;;
                    esac
                done

                for _celbridge_name in ${(k)_celbridge_snapshot}; do
                    export "$_celbridge_name=${_celbridge_snapshot[$_celbridge_name]}"
                done

                local -a _celbridge_folders
                _celbridge_folders=(${(s.:.)CELBRIDGE_CONSOLE_PATH_FOLDERS})
                path=($_celbridge_folders ${path:|_celbridge_folders})

                for _celbridge_name in {{string.Join(' ', PythonEnvironmentFilter.CommandNames)}}; do
                    unalias $_celbridge_name 2>/dev/null
                    unfunction $_celbridge_name 2>/dev/null
                done
                rehash

                # Point ZDOTDIR back at the user's folder, so a shell started from the console reads their files.
                if [[ -n $CELBRIDGE_CONSOLE_USER_ZDOTDIR || $_celbridge_user_zdotdir != $HOME ]]; then
                    export ZDOTDIR=$_celbridge_user_zdotdir
                else
                    unset ZDOTDIR
                fi

                unset -m '{{VariablePrefix}}*'
                unset _celbridge_snapshot _celbridge_zdotdir _celbridge_user_zdotdir

                # The console becomes visible at the marker. The command runs last, because nothing after it
                # would run until it exits.
                clear
                printf '{{ConsoleReadyMarker.PosixPrintfSource}}'
                if (( ${#_celbridge_command} )); then
                    "${_celbridge_command[@]}"
                fi
            }

            """;
    }

    private static string BuildBashRc()
    {
        return $$"""
            # {{Header}}

            # Save Celbridge's values before any start-up file can change them.
            for _celbridge_name in $CELBRIDGE_CONSOLE_RESTORE; do
                printf -v "_celbridge_saved_$_celbridge_name" '%s' "${!_celbridge_name}"
            done
            unset _celbridge_name

            if [ -r /etc/profile ]; then
                . /etc/profile
            fi

            # When the shell profile is on, run the first of the user's login files that exists, as a login shell does.
            if [ -n "${{UseShellProfileVariable}}" ]; then
                for _celbridge_file in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
                    if [ -r "$_celbridge_file" ]; then
                        . "$_celbridge_file"
                        break
                    fi
                done
                unset _celbridge_file
            fi

            # Runs once, just before the first prompt. Removes the uv and Python settings the start-up files added,
            # and restores Celbridge's. Then shows the console and runs its command. The last exit status is kept,
            # because a prompt may show it.
            _celbridge_first_prompt() {
                local _celbridge_status=$?
                local _celbridge_name _celbridge_saved _celbridge_folder _celbridge_index

                # Go back to the working folder, since a user's file may have changed it. Do this first, so the
                # restore below undoes anything a folder change set up. builtin skips any cd function the user
                # defined.
                local -a _celbridge_command=()
                local _celbridge_argument
                if [ -n "${{CommandVariable}}" ]; then
                    while IFS= read -r _celbridge_argument; do
                        _celbridge_command+=("$_celbridge_argument")
                    done <<< "${{CommandVariable}}"
                fi
                if [ -n "${{WorkingFolderVariable}}" ]; then
                    builtin cd -- "${{WorkingFolderVariable}}"
                fi

                for _celbridge_name in $(compgen -v); do
                    case $_celbridge_name in
                        {{ShellPattern(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) ;;
                        {{ShellPattern(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) unset "$_celbridge_name" ;;
                    esac
                done

                for _celbridge_name in $CELBRIDGE_CONSOLE_RESTORE; do
                    _celbridge_saved="_celbridge_saved_$_celbridge_name"
                    export "$_celbridge_name=${!_celbridge_saved}"
                    unset "$_celbridge_saved"
                done

                local -a _celbridge_folders
                IFS=: read -r -a _celbridge_folders <<< "$CELBRIDGE_CONSOLE_PATH_FOLDERS"
                for (( _celbridge_index = ${#_celbridge_folders[@]} - 1; _celbridge_index >= 0; _celbridge_index-- )); do
                    _celbridge_folder=${_celbridge_folders[_celbridge_index]}
                    if [ -z "$_celbridge_folder" ]; then
                        continue
                    fi
                    PATH=":$PATH:"
                    while [[ $PATH == *":$_celbridge_folder:"* ]]; do
                        PATH=${PATH//":$_celbridge_folder:"/:}
                    done
                    PATH=${PATH#:}
                    PATH=${PATH%:}
                    PATH="$_celbridge_folder${PATH:+:$PATH}"
                done

                for _celbridge_name in {{string.Join(' ', PythonEnvironmentFilter.CommandNames)}}; do
                    unalias "$_celbridge_name" 2>/dev/null
                    unset -f "$_celbridge_name" 2>/dev/null
                done
                hash -r

                # Replace this hook with the one that runs before every later prompt. That hook writes each command
                # to the history as it is entered, because closing a console kills the shell before it can save.
                # With the compact prompt on, it also sets the prompt, starting with this one.
                local _celbridge_lasting=$_celbridge_history_save
                if [ -n "$CELBRIDGE_CONSOLE_COMPACT_PROMPT" ]; then
                    _celbridge_lasting="$_celbridge_lasting${_celbridge_newline}_celbridge_compact_prompt"
                    _celbridge_compact_prompt
                fi
                if [ -n "$_celbridge_prompt_command_is_array" ]; then
                    PROMPT_COMMAND[${#PROMPT_COMMAND[@]}-1]=$_celbridge_lasting
                else
                    PROMPT_COMMAND="${_celbridge_prompt_command:+$_celbridge_prompt_command$_celbridge_newline}$_celbridge_lasting"
                fi
                unset _celbridge_prompt_command _celbridge_prompt_command_is_array _celbridge_newline _celbridge_history_save

                for _celbridge_name in ${!CELBRIDGE_CONSOLE_@}; do
                    unset "$_celbridge_name"
                done

                # The console becomes visible at the marker. The command runs last, because nothing after it
                # would run until it exits.
                clear
                printf '{{ConsoleReadyMarker.PosixPrintfSource}}'
                if [ ${#_celbridge_command[@]} -gt 0 ]; then
                    "${_celbridge_command[@]}"
                fi

                return $_celbridge_status
            }

            # Set before every prompt, because a prompt framework may rebuild its prompt before each one.
            if [ -n "$CELBRIDGE_CONSOLE_COMPACT_PROMPT" ]; then
                _celbridge_compact_prompt() {
                    PS1='{{BashCompactPrompt}}'
                }
            fi

            # Add the hook last, so it runs after any prompt commands the files added. A newline separates it,
            # because an existing prompt command may end in a semicolon.
            _celbridge_newline=$'\n'
            if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
                _celbridge_prompt_command_is_array=1
                PROMPT_COMMAND+=(_celbridge_first_prompt)
            else
                _celbridge_prompt_command=$PROMPT_COMMAND
                PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$_celbridge_newline}_celbridge_first_prompt"
            fi

            # bash loads the history after this file runs, so this history file wins over the others. Commands
            # are appended, so other consoles' commands are kept. macOS ships bash 3.2, which cannot append to a
            # file that was empty at start-up. In that case the whole file is written instead.
            _celbridge_history_save=:
            if [ -n "$CELBRIDGE_CONSOLE_HISTORY" ]; then
                HISTFILE=$CELBRIDGE_CONSOLE_HISTORY
                shopt -s histappend
                if [ -s "$HISTFILE" ]; then
                    _celbridge_history_save='history -a'
                else
                    _celbridge_history_save='history -w'
                fi
            fi
            """ + "\n";
    }

    // A case pattern matching any of the names exactly, or any name beginning with one of the prefixes.
    private static string ShellPattern(IReadOnlyList<string> names, IReadOnlyList<string> prefixes)
    {
        var alternatives = names.Concat(prefixes.Select(prefix => prefix + "*"));

        return string.Join('|', alternatives);
    }

    // A PowerShell condition that tests $celbridgeName. -eq and -like ignore case, as Windows does for variable
    // names.
    private static string PowerShellMatch(IReadOnlyList<string> names, IReadOnlyList<string> prefixes)
    {
        var conditions = names
            .Select(name => $"$celbridgeName -eq '{name}'")
            .Concat(prefixes.Select(prefix => $"$celbridgeName -like '{prefix}*'"));

        return string.Join(" -or ", conditions);
    }

    private static string PowerShellList(IReadOnlyList<string> values)
    {
        return string.Join(", ", values.Select(value => $"'{value}'"));
    }
}
