using Celbridge.Python.Services;

namespace Celbridge.Console.Helpers;

/// <summary>
/// One generated start-up file: its path under a mode's folder, and its content.
/// </summary>
public sealed record ConsoleStartupFile(string RelativePath, string Content);

/// <summary>
/// Generates the start-up files a console's shell runs, one set per mode. In pass-through mode they run the
/// user's own start-up files, then put Celbridge's settings back on top just before the first prompt. In clean
/// mode they run only the system's. The files hold rules alone: every value they act on reaches them through
/// the environment Celbridge starts the shell with, so no value from the user's environment is written to disk.
/// </summary>
public static class ConsoleStartupFiles
{
    /// <summary>
    /// The variable naming the variables Celbridge guarantees, which the start-up restores after the user's
    /// files have run.
    /// </summary>
    public const string RestoreVariable = "CELBRIDGE_CONSOLE_RESTORE";

    /// <summary>
    /// The variable naming the shell's history file.
    /// </summary>
    public const string HistoryVariable = "CELBRIDGE_CONSOLE_HISTORY";

    /// <summary>
    /// The variable naming the folder zsh would have read the user's own files from.
    /// </summary>
    public const string UserZdotdirVariable = "CELBRIDGE_CONSOLE_USER_ZDOTDIR";

    /// <summary>
    /// The prefix of every variable that only carries the start-up, which the start-up removes once it is done.
    /// </summary>
    public const string VariablePrefix = "CELBRIDGE_CONSOLE_";

    public const string ZshFolder = "zsh";
    public const string BashRcFile = "bash/bashrc";
    public const string PowerShellFile = "powershell/startup.ps1";

    private const string Header = "Generated by Celbridge when a console starts, which overwrites any change made here.";

    // zsh reads these from ZDOTDIR in this order, the first on every start and the rest in a login shell.
    private static readonly string[] ZshFileNames =
    {
        ".zshenv",
        ".zprofile",
        ".zshrc",
        ".zlogin",
    };

    /// <summary>
    /// The start-up files for one mode, for every shell a console runs.
    /// </summary>
    public static IReadOnlyList<ConsoleStartupFile> Generate(bool useShellProfile)
    {
        var files = new List<ConsoleStartupFile>();

        foreach (var fileName in ZshFileNames)
        {
            var content = BuildZshFile(fileName, useShellProfile);
            files.Add(new ConsoleStartupFile($"{ZshFolder}/{fileName}", content));
        }

        files.Add(new ConsoleStartupFile(BashRcFile, BuildBashRc(useShellProfile)));
        files.Add(new ConsoleStartupFile(PowerShellFile, BuildPowerShellStartup(useShellProfile)));

        return files;
    }

    /// <summary>
    /// The PowerShell start-up, which a console passes to PowerShell on its command line rather than as a
    /// script file, since an execution policy can refuse an unsigned script.
    /// </summary>
    public static string BuildPowerShellStartup(bool useShellProfile)
    {
        var profiles = useShellProfile ? PowerShellProfiles : string.Empty;

        return $$"""
            # {{Header}}
            # PowerShell receives this on its command line, so the copy on disk is for reading only.

            # The environment is still exactly what Celbridge built, so the values it guarantees are recorded
            # before any profile can change them.
            $global:CelbridgeSnapshot = @{}
            foreach ($celbridgeName in ("$env:{{RestoreVariable}}" -split ' ' | Where-Object { $_ })) {
                $global:CelbridgeSnapshot[$celbridgeName] = [Environment]::GetEnvironmentVariable($celbridgeName)
            }
            {{profiles}}
            if ($env:{{HistoryVariable}} -and (Get-Command Set-PSReadLineOption -ErrorAction SilentlyContinue)) {
                Set-PSReadLineOption -HistorySavePath $env:{{HistoryVariable}}
            }

            # Celbridge's settings go back on top just before the first prompt, after anything the profiles did.
            $global:CelbridgeUserPrompt = $function:prompt
            function global:prompt {
                foreach ($celbridgeVariable in @(Get-ChildItem Env:)) {
                    $celbridgeName = $celbridgeVariable.Name
                    if ({{PowerShellMatch(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) {
                        continue
                    }
                    if ({{PowerShellMatch(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) {
                        Remove-Item -LiteralPath "Env:$celbridgeName"
                    }
                }

                foreach ($celbridgeEntry in $global:CelbridgeSnapshot.GetEnumerator()) {
                    Set-Item -LiteralPath "Env:$($celbridgeEntry.Key)" -Value $celbridgeEntry.Value
                }

                $celbridgeFolders = @("$env:{{ConsoleEnvironmentVariables.PathFolders}}" -split ';' | Where-Object { $_ })
                $celbridgeRest = @("$env:Path" -split ';' | Where-Object { $_ -and $celbridgeFolders -notcontains $_ })
                $env:Path = ($celbridgeFolders + $celbridgeRest) -join ';'

                foreach ($celbridgeCommand in @({{PowerShellList(PythonEnvironmentFilter.CommandNames)}})) {
                    foreach ($celbridgeDrive in @('Alias', 'Function')) {
                        # An item can be defined in more than one scope, and each removal takes the nearest.
                        for ($celbridgeAttempt = 0; $celbridgeAttempt -lt 3; $celbridgeAttempt++) {
                            if (-not (Test-Path -LiteralPath "$($celbridgeDrive):$celbridgeCommand")) {
                                break
                            }
                            Remove-Item -LiteralPath "$($celbridgeDrive):$celbridgeCommand" -Force -ErrorAction SilentlyContinue
                        }
                    }
                }

                foreach ($celbridgeVariable in @(Get-ChildItem Env: | Where-Object { $_.Name -like '{{VariablePrefix}}*' })) {
                    Remove-Item -LiteralPath "Env:$($celbridgeVariable.Name)"
                }

                $celbridgePrompt = $global:CelbridgeUserPrompt
                Remove-Variable -Name CelbridgeSnapshot, CelbridgeUserPrompt -Scope Global
                $function:global:prompt = $celbridgePrompt
                & $celbridgePrompt
            }
            """;
    }

    // The profiles in the order PowerShell loads them. One that fails is reported and the rest still run, as
    // PowerShell's own loading does.
    private const string PowerShellProfiles = """

        # The profiles, in the order PowerShell loads them.
        foreach ($celbridgeProfile in @($PROFILE.AllUsersAllHosts, $PROFILE.AllUsersCurrentHost, $PROFILE.CurrentUserAllHosts, $PROFILE.CurrentUserCurrentHost)) {
            if ($celbridgeProfile -and (Test-Path -LiteralPath $celbridgeProfile)) {
                try {
                    . $celbridgeProfile
                }
                catch {
                    Write-Error $_
                }
            }
        }

        """;

    private static string BuildZshFile(string fileName, bool useShellProfile)
    {
        var lines = new List<string>
        {
            $"# {Header}",
            string.Empty,
        };

        if (fileName == ".zshenv")
        {
            lines.Add(ZshSnapshot);
        }

        if (useShellProfile)
        {
            lines.Add(ZshSourceUserFile(fileName));
        }

        if (fileName == ".zshenv")
        {
            // Registered here as well as in .zlogin, so an option in the user's .zshenv that stops zsh reading
            // the later files still leaves Celbridge's settings restored.
            lines.Add(BuildZshFirstPrompt());
            lines.Add("precmd_functions+=(_celbridge_first_prompt)");
        }

        if (fileName == ".zlogin")
        {
            lines.Add(ZshLastFile);
        }

        return string.Join('\n', lines) + '\n';
    }

    private const string ZshSnapshot = """
        # zsh reads this file first. The environment is still exactly what Celbridge built, so the values it
        # guarantees are recorded here, before any file of the user's can change them.
        typeset -gA _celbridge_snapshot
        for _celbridge_name in ${=CELBRIDGE_CONSOLE_RESTORE}; do
            _celbridge_snapshot[$_celbridge_name]=${(P)_celbridge_name}
        done
        unset _celbridge_name
        _celbridge_zdotdir=$ZDOTDIR
        _celbridge_user_zdotdir=${CELBRIDGE_CONSOLE_USER_ZDOTDIR:-$HOME}

        """;

    // The user's file runs at the top level rather than in a function, so a typeset in it stays global, and
    // with ZDOTDIR set to their own folder, as it would be in a terminal. Their .zshenv may move ZDOTDIR, and
    // their later files are then read from where it points.
    private static string ZshSourceUserFile(string fileName)
    {
        return $$"""
            ZDOTDIR=$_celbridge_user_zdotdir
            if [[ -r $ZDOTDIR/{{fileName}} ]]; then
                source $ZDOTDIR/{{fileName}}
            fi
            _celbridge_user_zdotdir=$ZDOTDIR
            ZDOTDIR=$_celbridge_zdotdir

            """;
    }

    private const string ZshLastFile = """
        # Moved to the end of the prompt hooks, so it runs after every hook the user's files installed.
        precmd_functions=(${precmd_functions:#_celbridge_first_prompt} _celbridge_first_prompt)

        # zsh reads the history once its start-up files have run, so this overrides a history file the user's
        # files chose. Each command is written as it is entered, since closing a console ends its shell before
        # the shell can save.
        if [[ -n $CELBRIDGE_CONSOLE_HISTORY ]]; then
            HISTFILE=$CELBRIDGE_CONSOLE_HISTORY
            if (( ! SAVEHIST )); then
                SAVEHIST=1000
            fi
            if (( HISTSIZE < SAVEHIST )); then
                HISTSIZE=$SAVEHIST
            fi
            setopt INC_APPEND_HISTORY
        fi
        """;

    private static string BuildZshFirstPrompt()
    {
        return $$"""
            # Runs once, just before the first prompt: the uv and Python settings the user's files made go, and
            # Celbridge's go back on top.
            _celbridge_first_prompt() {
                precmd_functions=(${precmd_functions:#_celbridge_first_prompt})

                local _celbridge_name
                for _celbridge_name in ${(k)parameters}; do
                    case $_celbridge_name in
                        ({{ShellPattern(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) ;;
                        ({{ShellPattern(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) unset $_celbridge_name ;;
                    esac
                done

                for _celbridge_name in ${(k)_celbridge_snapshot}; do
                    export "$_celbridge_name=${_celbridge_snapshot[$_celbridge_name]}"
                done

                local -a _celbridge_folders
                _celbridge_folders=(${(s.:.)CELBRIDGE_CONSOLE_PATH_FOLDERS})
                path=($_celbridge_folders ${path:|_celbridge_folders})

                for _celbridge_name in {{string.Join(' ', PythonEnvironmentFilter.CommandNames)}}; do
                    unalias $_celbridge_name 2>/dev/null
                    unfunction $_celbridge_name 2>/dev/null
                done
                rehash

                # Anything started from the console reads the user's own files, from where they keep them.
                if [[ -n $CELBRIDGE_CONSOLE_USER_ZDOTDIR || $_celbridge_user_zdotdir != $HOME ]]; then
                    export ZDOTDIR=$_celbridge_user_zdotdir
                else
                    unset ZDOTDIR
                fi

                unset -m '{{VariablePrefix}}*'
                unset _celbridge_snapshot _celbridge_zdotdir _celbridge_user_zdotdir
            }

            """;
    }

    private static string BuildBashRc(bool useShellProfile)
    {
        var userFiles = useShellProfile ? BashUserFiles : string.Empty;

        return $$"""
            # {{Header}}

            # The environment is still exactly what Celbridge built, so the values it guarantees are recorded
            # before any file can change them.
            for _celbridge_name in $CELBRIDGE_CONSOLE_RESTORE; do
                printf -v "_celbridge_saved_$_celbridge_name" '%s' "${!_celbridge_name}"
            done
            unset _celbridge_name

            if [ -r /etc/profile ]; then
                . /etc/profile
            fi
            {{userFiles}}
            # Runs once, just before the first prompt: the uv and Python settings the files made go, and
            # Celbridge's go back on top. The exit status is kept, since a prompt may show it.
            _celbridge_first_prompt() {
                local _celbridge_status=$?
                local _celbridge_name _celbridge_saved _celbridge_folder _celbridge_index

                for _celbridge_name in $(compgen -v); do
                    case $_celbridge_name in
                        {{ShellPattern(PythonEnvironmentFilter.KeptNames, PythonEnvironmentFilter.KeptPrefixes)}}) ;;
                        {{ShellPattern(PythonEnvironmentFilter.RemovedNames, PythonEnvironmentFilter.RemovedPrefixes)}}) unset "$_celbridge_name" ;;
                    esac
                done

                for _celbridge_name in $CELBRIDGE_CONSOLE_RESTORE; do
                    _celbridge_saved="_celbridge_saved_$_celbridge_name"
                    export "$_celbridge_name=${!_celbridge_saved}"
                    unset "$_celbridge_saved"
                done

                local -a _celbridge_folders
                IFS=: read -r -a _celbridge_folders <<< "$CELBRIDGE_CONSOLE_PATH_FOLDERS"
                for (( _celbridge_index = ${#_celbridge_folders[@]} - 1; _celbridge_index >= 0; _celbridge_index-- )); do
                    _celbridge_folder=${_celbridge_folders[_celbridge_index]}
                    if [ -z "$_celbridge_folder" ]; then
                        continue
                    fi
                    PATH=":$PATH:"
                    while [[ $PATH == *":$_celbridge_folder:"* ]]; do
                        PATH=${PATH//":$_celbridge_folder:"/:}
                    done
                    PATH=${PATH#:}
                    PATH=${PATH%:}
                    PATH="$_celbridge_folder${PATH:+:$PATH}"
                done

                for _celbridge_name in {{string.Join(' ', PythonEnvironmentFilter.CommandNames)}}; do
                    unalias "$_celbridge_name" 2>/dev/null
                    unset -f "$_celbridge_name" 2>/dev/null
                done
                hash -r

                # The hook's place goes to writing each command to the history as it is entered, since closing a
                # console ends its shell before the shell can save.
                if [ -n "$_celbridge_prompt_command_is_array" ]; then
                    PROMPT_COMMAND[${#PROMPT_COMMAND[@]}-1]=$_celbridge_history_save
                else
                    PROMPT_COMMAND="${_celbridge_prompt_command:+$_celbridge_prompt_command$_celbridge_newline}$_celbridge_history_save"
                fi
                unset _celbridge_prompt_command _celbridge_prompt_command_is_array _celbridge_newline _celbridge_history_save

                for _celbridge_name in ${!CELBRIDGE_CONSOLE_@}; do
                    unset "$_celbridge_name"
                done

                return $_celbridge_status
            }

            # Added last, so it runs after every prompt command the files installed. A newline separates it,
            # since a prompt command may end in a semicolon.
            _celbridge_newline=$'\n'
            if [[ "$(declare -p PROMPT_COMMAND 2>/dev/null)" == "declare -a"* ]]; then
                _celbridge_prompt_command_is_array=1
                PROMPT_COMMAND+=(_celbridge_first_prompt)
            else
                _celbridge_prompt_command=$PROMPT_COMMAND
                PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$_celbridge_newline}_celbridge_first_prompt"
            fi

            # bash reads the history once this file has run, so this overrides a history file the other files
            # chose. Another console's commands are appended to rather than overwritten. bash 3.2, which macOS
            # ships, appends nothing to a file that was empty when the session started, so a first session
            # rewrites the file instead.
            _celbridge_history_save=:
            if [ -n "$CELBRIDGE_CONSOLE_HISTORY" ]; then
                HISTFILE=$CELBRIDGE_CONSOLE_HISTORY
                shopt -s histappend
                if [ -s "$HISTFILE" ]; then
                    _celbridge_history_save='history -a'
                else
                    _celbridge_history_save='history -w'
                fi
            fi
            """ + "\n";
    }

    // The user's login files, as a login shell reads them: the first of these that exists.
    private const string BashUserFiles = """

        for _celbridge_file in "$HOME/.bash_profile" "$HOME/.bash_login" "$HOME/.profile"; do
            if [ -r "$_celbridge_file" ]; then
                . "$_celbridge_file"
                break
            fi
        done
        unset _celbridge_file

        """;

    // A case pattern matching any of the names exactly, or any name beginning with one of the prefixes.
    private static string ShellPattern(IReadOnlyList<string> names, IReadOnlyList<string> prefixes)
    {
        var alternatives = names.Concat(prefixes.Select(prefix => prefix + "*"));

        return string.Join('|', alternatives);
    }

    // A PowerShell condition on $celbridgeName, which -eq and -like compare ignoring case, as Windows does.
    private static string PowerShellMatch(IReadOnlyList<string> names, IReadOnlyList<string> prefixes)
    {
        var conditions = names
            .Select(name => $"$celbridgeName -eq '{name}'")
            .Concat(prefixes.Select(prefix => $"$celbridgeName -like '{prefix}*'"));

        return string.Join(" -or ", conditions);
    }

    private static string PowerShellList(IReadOnlyList<string> values)
    {
        return string.Join(", ", values.Select(value => $"'{value}'"));
    }
}
