[document]
id = "scene-viewer-document"
type = "custom"
entry_point = "index.html"
priority = "specialized"
external_content = true
display_name = "SceneViewer_Editor_Name"

[[document_file_types]]
extension = ".scene"
display_name = "SceneViewer_FileType_Scene"
