[document]
id = "spreadsheet-document"
type = "custom"
entry_point = "index.html"
priority = "general"
binary = true

[[document_file_types]]
extension = ".xlsx"
display_name = "Spreadsheet_FileType_Xlsx"
