[document]
id = "note-document"
type = "custom"
entry_point = "index.html"
priority = "specialized"

[[document_file_types]]
extension = ".note"
display_name = "Note_FileType_Note"

[[document_templates]]
id = "empty"
display_name = "Note_Template_Empty"
template_file = "templates/empty.note"
default = true
